### ISSUE TITLE
[不具合]SsKeyBindingEditorの不具合

### ISSUE THREAD

**Issue by hirotaka-takeuchi** [SpriteStudio/SsKeyBindingEditor#8]
・SsKeyBindingEditorの起動時にSsStringTable.ja.datが読み込み失敗というダイアログがでて日本語化されない
・起動後ショートカットキーのリストのどれかを変更、または保存を押すなどするとアプリがクラッシュする。
・設定したショートカットキーがSS6で一度そのショートカットを使うとそれ以降そのショートカットがデフォルトに戻る

**Comment by AkaneSera** [comment]
ウェブテクノロジ　瀬良です。
ご報告いただきありがとうございます。

SpriteStudio Ver.6をご利用とのことですが、こちらの「SsKeyBindingEditor」はSpriteStudio 5 用になります。SpriteStudio Ver.6のコマンドにも対応したSsKeyBindingEditorは「SsKeyBindingEditorV6」となります。

▼SsKeyBindingEditorV6はこちらです
https://github.com/SpriteStudio/SsKeyBindingEditorV6

お手数おかけし恐れ入りますが、ご利用のSpriteStudioとSsKeyBindingEditorのバージョンをお確かめいただければ幸いです。

―――

また、バージョンが合っているにも関わらず、諸症状が発生している場合、ショートカットキーの設定ファイル「SsKeyBindings.xml」をご提供いただくことはできないでしょうか。

SsKeyBindings.xmlは以下にございます。

Windowsの場合：
/Documents/SpriteStudio

macOSの場合：
/書類/SpriteStudio/

ご送付いただく際に

・ご利用のSpriteStudioのバージョン
・SsKeyBindingEditorのバージョン
・ご利用のOS

も併せてお知らせくださいませ。

●GitHubに添付が難しい場合

SpriteStudioTechSupport@webtech.co.jp
宛てにご送付いただければ幸いでございます。

ご迷惑をおかけしている中重ね重ね恐縮ではございますが
何卒よろしくお願いいたします。

**Comment by hirotaka-takeuchi** [comment]
・SsKeyBindingEditorの起動時にSsStringTable.ja.datが読み込み失敗というダイアログがでて日本語化されない
・起動後ショートカットキーのリストのどれかを変更、または保存を押すなどするとアプリがクラッシュする。
上記２件はバージョン違いによるものでした、もうしわけありません。


・設定したショートカットキーがSS6起動後、一度そのショートカットを使うとそれ以降そのショートカットがデフォルトに戻る
上記１件はSsKeyBindingEditor の方の不具合のためそちらにissueをあげたいとおもいます。
一度クローズさせていただきます。
